homework1
Inkin88/teamcity pull request #1
Opened 2023-12-04 00:35 UTC by Inkin88

2023-12-08 19:31 UTC, AlexPshe requested changes
Привет!

Большое спасибо за качественное выполнение задания!

Я добавила несколько комментов по улучшению - нужно пофиксить их за неделю и будет зачтено ⚡️

2023-12-08 19:31 UTC, AlexPshe commented on .mvn/wrapper/maven-wrapper.properties
> +wrapperUrl=https://repo.maven.apache.org/maven2/org/apache/maven/wrapper/maven-wrapper/3.1.0/maven-wrapper-3.1.0.jar
Папку `.idea` не нужно коммитить, в ней хранятся настройки самой IDE, не код 🙌

2023-12-08 19:31 UTC, AlexPshe commented on src/main/java/ru/muzafarov/teamcity/api/models/NewProjectDescription.java
> +
Форматинг: пустая строка

2023-12-08 19:31 UTC, AlexPshe commented on test-cases/smoke-test.md
> +# Smoke_Test
Лайк за TMS)

2023-12-08 21:23 UTC, AlexPshe requested changes

2023-12-08 21:23 UTC, AlexPshe commented on src/main/java/ru/muzafarov/teamcity/api/config/Config.java
> +                System.err.println("File not found" + CONFIG_PROPERTIES);
Можно тут использовать `format`, как ты успешно делал в других примерах.

2023-12-08 21:23 UTC, AlexPshe commented on src/main/java/ru/muzafarov/teamcity/api/requests/checked/AuthRequest.java
> +                .get("/authenticationTest.html?csrf")
В константу можно вынести

2023-12-08 21:23 UTC, AlexPshe commented on src/main/java/ru/muzafarov/teamcity/api/requests/checked/CheckedBuildConfigRequests.java
> +public class CheckedBuildConfigRequests extends Request implements CrudInterface {
Если успешно выполнил на этом этапе запросы, давай параметризуем их по моделям теперь ⚡️

2023-12-08 21:23 UTC, AlexPshe commented on src/test/java/ru/muzafarov/teamcity/api/project/CreateBuildConfigurationTest.java
> +        unCheckedWithSuperUserRequest.getUncheckedBuildReq().create(testData.getBuildType())
А само сообщение об ошибке не проверил)

2023-12-12 09:06 UTC, Inkin88 commented on .mvn/wrapper/maven-wrapper.properties
> +wrapperUrl=https://repo.maven.apache.org/maven2/org/apache/maven/wrapper/maven-wrapper/3.1.0/maven-wrapper-3.1.0.jar
Удалил.

2023-12-12 09:07 UTC, Inkin88 commented on src/main/java/ru/muzafarov/teamcity/api/models/NewProjectDescription.java
> +
Fixed

2023-12-12 09:07 UTC, Inkin88 commented on src/main/java/ru/muzafarov/teamcity/api/config/Config.java
> +                System.err.println("File not found" + CONFIG_PROPERTIES);
fixed

2023-12-12 09:07 UTC, Inkin88 commented on src/main/java/ru/muzafarov/teamcity/api/requests/checked/AuthRequest.java
> +                .get("/authenticationTest.html?csrf")
fixed

2023-12-12 09:08 UTC, Inkin88 commented on src/main/java/ru/muzafarov/teamcity/api/requests/checked/CheckedBuildConfigRequests.java
> +public class CheckedBuildConfigRequests extends Request implements CrudInterface {
Реализовано через CheckedBase и UnchekedBase

2023-12-12 09:08 UTC, Inkin88 commented on src/test/java/ru/muzafarov/teamcity/api/project/CreateBuildConfigurationTest.java
> +        unCheckedWithSuperUserRequest.getUncheckedBuildReq().create(testData.getBuildType())
Изначально так и задумывалось, т.к. не знаю какое сообщение. Включил воображение, добавил сообщение.

2023-12-12 09:11 UTC, AlexPshe approved these changes
Огонь! 
Advanced версия засчитана, но есть еще advanced уровня №2 c параметризацией интерфейсов, поэтому давай тоже попробуем реализовать 📈

2023-12-12 09:11 UTC, AlexPshe commented on src/main/java/ru/muzafarov/teamcity/api/requests/GetDetailsInterface.java
> +    Object getList(String typeList);
Тут будет возвращаться List<T> и также параметризуется моделью

2023-12-12 09:11 UTC, AlexPshe commented on src/main/java/ru/muzafarov/teamcity/api/requests/checked/CheckedBase.java
> +public class CheckedBase<T> extends Request implements CrudInterface, GetDetailsInterface {
Огонь! И теперь самый последний шаг: 
параметризовать списком интерфейсов, то есть мы будем создавать один запрос через: 
`new UncheckedBase(spec, "/app/rest/buildTypes", список интерфейсов)`

2023-12-17 14:04 UTC, merged